---
- name: Git Clone RPI_LCD scripts
  ansible.builtin.git:
    repo: https://github.com/waveshare/LCD-show.git
    dest: LCD-show
    version: master
    force: yes

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: LCD-show/LCD32C-show
    mode: '0744'

- name: Prevent LCD32-show to reboot
  ansible.builtin.lineinfile:
    path: LCD-show/LCD32C-show
    regexp: '^sudo reboot'
    line: \# sudo reboot

- name: Enable LCD
  ansible.builtin.command:
    cmd: sudo LCD-show/LCD32C-show

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: Rotate LCD 180
  ansible.builtin.command:
    cmd: sudo LCD-show/LCD32C-show 180

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami