---
- name: Setup Raspberry Pi
  hosts: raspberry

  vars_prompt:
    - name: "APT_UPDATE"
      prompt: "Update Packages (default=no)?"
      private: false
    - name: "RPi_LCD_C"
      prompt: "3_2inch_RPi_LCD_C (default=no)?"
      private: false

  roles:
    - common
    - apt-update
    #- ajenti
    #- adguard
    - rpi_lcd
