---
- name: Download Install script
  get_url:
    url: https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh
    dest: ./install.sh
    mode: '0744'

- name: Install
  ansible.builtin.command:
    cmd: ./install.sh -v
